def has_attribute(bases, attrs, name):
    """Returns whether a class that is generated by a metaclass will have an
    attribute with the given name.

    :param bases: the base classes of the generated class
    :type bases: tuple
    :param attrs: the attributes of the generated class
    :type attrs: dict
    :param name: the name of the desired attribute
    :type name: str
    :rtype: bool
    """
    if name in attrs:
        return True
    for base in bases:
        if hasattr(base, name):
            return True
    return False
